apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      ver: v1.0
  template:
    metadata:
      labels:
        app: web
        ver: v1.0
    spec:
      containers:
        - name: web
          image: kandula17/devops-external:master
          ports:
            - containerPort: 8080
          env:
          - name: SERVER
            value: "http://api-svc:8082"


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-svc
  name: web-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
   app: web
   ver: v1.0
  type: LoadBalancer
